name: Inazuma Akyelken Build
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libncurses5-dev libelf-dev flex bison git

      - name: Download Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export PATH="${GITHUB_WORKSPACE}/clang/bin:${PATH}"
          
          make mrproper
          make pdx203_defconfig
          
          # Derlemeyi zorla ve hataları görmezden gel (Sadece kritik hatalarda durur)
          make -j$(nproc --all) \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            CONFIG_NO_ERROR_ON_MISMATCH=y \
            Image.gz dtbo.img
