name: Inazuma Akyelken Build
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Env
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libncurses5-dev libelf-dev flex bison git

      - name: Get Proton Clang
        run: git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Build Kernel
        run: |
          export PATH="${GITHUB_WORKSPACE}/clang/bin:${PATH}"
          make O=out ARCH=arm64 pdx203_defconfig
          # En sağlam derleme metodu: LLVM=1
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LLVM=1 \
            LLVM_IAS=1 \
            Image.gz dtbo.img
